// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeeD59m4ETARmFKCVEWVz7X5_7qzzD1HQ',
    appId: '1:549517049446:web:3f68ccebe27d1af1bff7a7',
    messagingSenderId: '549517049446',
    projectId: 'enim-press',
    authDomain: 'enim-press.firebaseapp.com',
    storageBucket: 'enim-press.appspot.com',
    measurementId: 'G-FYLJBZDYZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWxFunkbiVHt0aCiFsYrg-ALsV1gWsLsQ',
    appId: '1:549517049446:android:4dca40231a41b2cfbff7a7',
    messagingSenderId: '549517049446',
    projectId: 'enim-press',
    storageBucket: 'enim-press.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2254kKXHaD6j6_yoKM1EqGqmaxT09cno',
    appId: '1:549517049446:ios:84e32ce48bc5bb69bff7a7',
    messagingSenderId: '549517049446',
    projectId: 'enim-press',
    storageBucket: 'enim-press.appspot.com',
    iosClientId: '549517049446-gc1mre3560v0adt2q4padj4h56dl6rsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.enimPress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2254kKXHaD6j6_yoKM1EqGqmaxT09cno',
    appId: '1:549517049446:ios:84e32ce48bc5bb69bff7a7',
    messagingSenderId: '549517049446',
    projectId: 'enim-press',
    storageBucket: 'enim-press.appspot.com',
    iosClientId: '549517049446-gc1mre3560v0adt2q4padj4h56dl6rsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.enimPress',
  );
}
